name: Trigger Deployment

on:
  push:
    branches: [main]

jobs:
  ping-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Notify To Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: wdc-ui/wdc-ops
          event-type: deploy_event
